# Generated by Django 5.0.2 on 2024-02-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'manager'), ('team_leader', 'team_leader'), ('developer', 'developer')], default='manager', max_length=45),
        ),
    ]
